package t1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-03-17T11:40:43.308+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://online.webservice.crystalreport.project.transglobe.ebizprise.com/", name = "KernelOnlineService")
@XmlSeeAlso({ObjectFactory.class})
public interface KernelOnlineService {

    @WebMethod
    @RequestWrapper(localName = "downloadFile", targetNamespace = "http://online.webservice.crystalreport.project.transglobe.ebizprise.com/", className = "t1.DownloadFile")
    @ResponseWrapper(localName = "downloadFileResponse", targetNamespace = "http://online.webservice.crystalreport.project.transglobe.ebizprise.com/", className = "t1.DownloadFileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public t1.OnlineReportGenResponse downloadFile(
        @WebParam(name = "OnlineKernelGenRequest", targetNamespace = "")
        t1.OnlineKernelGenRequest onlineKernelGenRequest
    );
}
